# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

RunModularityClusteringCpp <- function(SNN, modularityFunction, resolution, algorithm, nRandomStarts, nIterations, randomSeed, printOutput, edgefilename) {
    .Call('_CellLabeler_RunModularityClusteringCpp', PACKAGE = 'CellLabeler', SNN, modularityFunction, resolution, algorithm, nRandomStarts, nIterations, randomSeed, printOutput, edgefilename)
}

fastOrder <- function(Ar, Br) {
    .Call('_CellLabeler_fastOrder', PACKAGE = 'CellLabeler', Ar, Br)
}

fastPDist <- function(Ar, Br) {
    .Call('_CellLabeler_fastPDist', PACKAGE = 'CellLabeler', Ar, Br)
}

MCAStep1 <- function(X) {
    .Call('_CellLabeler_MCAStep1', PACKAGE = 'CellLabeler', X)
}

MCAStep2 <- function(Z, V, Dc) {
    .Call('_CellLabeler_MCAStep2', PACKAGE = 'CellLabeler', Z, V, Dc)
}

RunUMISampling <- function(data, sample_val, upsample = FALSE, display_progress = TRUE) {
    .Call('_CellLabeler_RunUMISampling', PACKAGE = 'CellLabeler', data, sample_val, upsample, display_progress)
}

RunUMISamplingPerCell <- function(data, sample_val, upsample = FALSE, display_progress = TRUE) {
    .Call('_CellLabeler_RunUMISamplingPerCell', PACKAGE = 'CellLabeler', data, sample_val, upsample, display_progress)
}

RowMergeMatrices <- function(mat1, mat2, mat1_rownames, mat2_rownames, all_rownames) {
    .Call('_CellLabeler_RowMergeMatrices', PACKAGE = 'CellLabeler', mat1, mat2, mat1_rownames, mat2_rownames, all_rownames)
}

LogLibSizeFactorNorm <- function(data, scale_factor, display_progress = TRUE) {
    .Call('_CellLabeler_LogLibSizeFactorNorm', PACKAGE = 'CellLabeler', data, scale_factor, display_progress)
}

LogSizeFactorNorm <- function(data, size_factor, pseudo_count, display_progress = TRUE) {
    .Call('_CellLabeler_LogSizeFactorNorm', PACKAGE = 'CellLabeler', data, size_factor, pseudo_count, display_progress)
}

Standardize <- function(mat, display_progress = TRUE) {
    .Call('_CellLabeler_Standardize', PACKAGE = 'CellLabeler', mat, display_progress)
}

FastSparseRowScale <- function(mat, scale = TRUE, center = TRUE, scale_max = 10, display_progress = TRUE) {
    .Call('_CellLabeler_FastSparseRowScale', PACKAGE = 'CellLabeler', mat, scale, center, scale_max, display_progress)
}

FastSparseRowScaleWithKnownStats <- function(mat, mu, sigma, scale = TRUE, center = TRUE, scale_max = 10, display_progress = TRUE) {
    .Call('_CellLabeler_FastSparseRowScaleWithKnownStats', PACKAGE = 'CellLabeler', mat, mu, sigma, scale, center, scale_max, display_progress)
}

FastCov <- function(mat, center = TRUE) {
    .Call('_CellLabeler_FastCov', PACKAGE = 'CellLabeler', mat, center)
}

FastCovMats <- function(mat1, mat2, center = TRUE) {
    .Call('_CellLabeler_FastCovMats', PACKAGE = 'CellLabeler', mat1, mat2, center)
}

FastRBind <- function(mat1, mat2) {
    .Call('_CellLabeler_FastRBind', PACKAGE = 'CellLabeler', mat1, mat2)
}

FastExpMean <- function(mat, display_progress) {
    .Call('_CellLabeler_FastExpMean', PACKAGE = 'CellLabeler', mat, display_progress)
}

SparseRowVar2 <- function(mat, mu, display_progress) {
    .Call('_CellLabeler_SparseRowVar2', PACKAGE = 'CellLabeler', mat, mu, display_progress)
}

SparseRowVarStd <- function(mat, mu, sd, vmax, display_progress) {
    .Call('_CellLabeler_SparseRowVarStd', PACKAGE = 'CellLabeler', mat, mu, sd, vmax, display_progress)
}

FastLogVMR <- function(mat, display_progress) {
    .Call('_CellLabeler_FastLogVMR', PACKAGE = 'CellLabeler', mat, display_progress)
}

FastRowVar <- function(x) {
    .Call('_CellLabeler_FastRowVar', PACKAGE = 'CellLabeler', x)
}

FastRowMean <- function(x) {
    .Call('_CellLabeler_FastRowMean', PACKAGE = 'CellLabeler', x)
}

FastSparseRowVar <- function(mat) {
    .Call('_CellLabeler_FastSparseRowVar', PACKAGE = 'CellLabeler', mat)
}

FastSparseRowMean <- function(mat) {
    .Call('_CellLabeler_FastSparseRowMean', PACKAGE = 'CellLabeler', mat)
}

ReplaceColsC <- function(mat, col_idx, replacement) {
    .Call('_CellLabeler_ReplaceColsC', PACKAGE = 'CellLabeler', mat, col_idx, replacement)
}

GraphToNeighborHelper <- function(mat) {
    .Call('_CellLabeler_GraphToNeighborHelper', PACKAGE = 'CellLabeler', mat)
}

RowVarRcpp <- function(x) {
    .Call('_CellLabeler_RowVarRcpp', PACKAGE = 'CellLabeler', x)
}

#' ComputeSNN of a given matrix
#'
#' @param nn_ranked A symmetric matrix
#' @export
ComputeSNN <- function(nn_ranked, prune) {
    .Call('_CellLabeler_ComputeSNN', PACKAGE = 'CellLabeler', nn_ranked, prune)
}

WriteEdgeFile <- function(snn, filename, display_progress) {
    invisible(.Call('_CellLabeler_WriteEdgeFile', PACKAGE = 'CellLabeler', snn, filename, display_progress))
}

DirectSNNToFile <- function(nn_ranked, prune, display_progress, filename) {
    .Call('_CellLabeler_DirectSNNToFile', PACKAGE = 'CellLabeler', nn_ranked, prune, display_progress, filename)
}

SNN_SmallestNonzero_Dist <- function(snn, mat, n, nearest_dist) {
    .Call('_CellLabeler_SNN_SmallestNonzero_Dist', PACKAGE = 'CellLabeler', snn, mat, n, nearest_dist)
}

#' Graph Laplacian calculation
#'
#' Calculate graph Laplacian of a symmetrix matrix
#'
#' @param A symmetric matrix
#' @export
LaplacianMat <- function(A, sigma, alpha) {
    .Call('_CellLabeler_LaplacianMat', PACKAGE = 'CellLabeler', A, sigma, alpha)
}

MultiplyMat <- function(Xin, Yin) {
    .Call('_CellLabeler_MultiplyMat', PACKAGE = 'CellLabeler', Xin, Yin)
}

#' Compute Euclidean distance matrix by columns
#'
#' Used in sc3-funcs.R distance matrix calculation
#' and within the consensus clustering.
#'
#' @param x A numeric matrix.
ED2 <- function(x) {
    .Call('_CellLabeler_ED2', PACKAGE = 'CellLabeler', x)
}

#' Euclidean distance calculation
#'
#' Calculate graph Laplacian of a symmetrix matrix
#'
#' @param A symmetric matrix
#' @export
parsesED2 <- function(X, num_core) {
    .Call('_CellLabeler_parsesED2', PACKAGE = 'CellLabeler', X, num_core)
}

DistEuc <- function(Xin, Yin) {
    .Call('_CellLabeler_DistEuc', PACKAGE = 'CellLabeler', Xin, Yin)
}

#' Consensus matrix computation
#'
#' Computes consensus matrix given cluster labels
#'
#' @param dat a matrix containing clustering solutions in columns
consmx <- function(dat) {
    .Call('_CellLabeler_consmx', PACKAGE = 'CellLabeler', dat)
}

#' FastMap for dimension reduction, SIGMOD '95: Proceedings of the 1995 ACM SIGMOD international conference on Management of data
#' June 1995 Pages 163–174; DOI: https://doi.org/10.1145/223784.223812
#'
#' Computes reduced dimension with linear computation time
#'
#' @param D Distance matrix
#' 
#' @param dat a matrix containing clustering solutions in columns
FastMapEculidean <- function(D, num_dim) {
    .Call('_CellLabeler_FastMapEculidean', PACKAGE = 'CellLabeler', D, num_dim)
}

DistEigenTestRcpp <- function(Xin) {
    .Call('_CellLabeler_DistEigenTestRcpp', PACKAGE = 'CellLabeler', Xin)
}

